name: Endor Labs Dependency and Secrets Scan
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  MAVEN_OPTS: "-Dmaven.repo.local=./local/test/.m2/repository"
  ENDOR_MAVEN_ADDITIONAL_PAREMETERS: "-Dmaven.repo.local=./local/test/.m2/repository"
jobs:
  scan-main-cold-cache:
    permissions:
      contents: read
    name: cold-cache-scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build with maven
      run: |
        mkdir -p ./local/test/.m2/repository
        mvn -U clean install -s settings.xml -Dmaven.test.skip=true -DskipTests -q
    - name: Install endorctl and scan
      env:
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          ENDOR_NAMESPACE: endor-solutions-tgood.test
      run: |
         curl -fsSL https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o ./endorctl
         chmod +x ./endorctl
         ./endorctl --version
         ./endorctl scan --dependencies --quick-scan --disable-private-package-analysis --use-local-repo-cache --languages java 
  scan-main-WARM-cache:
    permissions:
      contents: read
    name: WARM-cache-scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build with maven
      run: |
        mkdir -p ./local/test/.m2/repository
        mvn -U clean install -s settings.xml -Dmaven.test.skip=true -DskipTests -q
    - name: Warm the cache
      run: |
        mvn help:effective-pom -N -s settings.xml -q
        mvn dependency:tree    -N -s settings.xml -q
    - name: mvn -ntp
      run: mvn -ntp help:effective-pom -f pom.xml -Doutput=/tmp/epom-test.xml -N --offline -Daether.dependencyCollector.impl=bf
    - name: Install endorctl and scan
      env:
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          ENDOR_NAMESPACE: endor-solutions-tgood.test
      run: |
         curl -fsSL https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o ./endorctl
         chmod +x ./endorctl
         ./endorctl --version
         ./endorctl scan --dependencies --quick-scan --disable-private-package-analysis --use-local-repo-cache --languages java --log-level=debug
    