name: Endor Labs Dependency and Secrets Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  scan-main:
    permissions:
      contents: read
    name: endorctl-scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build with maven
      run: mvn clean install
    - name: Install endorctl
      run: curl -fsSL https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o /usr/local/bin/endorctl
          chmod +x /usr/local/bin/endorctl
          endorctl --version
    - name: Scan with endorctl
      env:
          ENDOR_API_CREDENTIALS_KEY: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
          ENDOR_API_CREDENTIALS_SECRET: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
          ENDOR_NAMESPACE: endor-solutions-tgood.test
      run: |
          endorctl scan \
            --languages=java \
            --secrets=false